// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Form(started bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"form\" hx-post=\"/start\" hx-swap=\"none\" class=\"w-full h-full flex flex-col items-center justify-center\" hx-on=\"submit: event.preventDefault()\"><div class=\"w-2/3 flex flex-col items-center\"><label for=\"token\" class=\"font-bold self-start\">Bearer token</label> <input type=\"text\" name=\"token\" placeholder=\"Bearer &lt;token&gt;\" class=\"block w-full p-2 mt-2 mb-6 bg-[#535C91]\" required=\"true\"></div><div class=\"w-2/3 flex flex-col items-center\"><label for=\"ecrn\" class=\"font-bold self-start\">Alınacak Dersler</label> <input type=\"text\" name=\"ecrn\" placeholder=\"CRN1,CRN2,CRN3\" class=\"block w-full p-2 mt-2 mb-6 bg-[#535C91]\" required=\"true\"></div><div class=\"w-2/3 flex flex-col items-center\"><label for=\"scrn\" class=\"font-bold self-start\">Bırakılacak Dersler</label> <input type=\"text\" name=\"scrn\" placeholder=\"CRN1,CRN2,CRN3\" class=\"block w-full p-2 mt-2 mb-6 bg-[#535C91]\" required=\"true\"></div><div class=\"w-2/3 flex flex-col items-center\"><label for=\"timeout\" class=\"font-bold self-start\">İstek aralığı</label> <input type=\"text\" name=\"timeout\" placeholder=\"Süre\" class=\"block w-full p-2 mt-2 mb-6 bg-[#535C91]\" required=\"true\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = FormButtons(started).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func FormButtons(started bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div id=\"form-buttons\" class=\"w-full flex justify-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !started {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<button type=\"submit\" class=\"block w-2/3 p-2 m-2 bg-blue-500 text-white hover:cursor-pointer\">Başlat</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"flex space-x-2\"><button class=\"block w-1/2 p-2 m-2 bg-gray-800 text-white hover:cursor-disabled\" disabled=\"true\">Başlat</button> <button hx-get=\"/stop\" hx-swap=\"none\" class=\"block w-1/2 p-2 m-2 bg-red-500 text-white hover:cursor-pointer\">Durdur</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
